### ISSUE TITLE
Explain that you can delete npm installs from the bash script to save time and space.

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/how-to-share-code-between-apify-actors#1]

**Comment by drobnikj** [comment]
I think you need to run npm install to install the latest shared version to node_modules. Did it work without that?

**Comment by metalwarrior665** [comment]
I think that would make sense only if you upgraded the version. But since everything is deleted and the build again I think it works fine without install. At least it worked for me in my repo when I was changing the shared code without changing any version numbers.

**Comment by metalwarrior665** [comment]
Actually, you are right. I first tested it on Apify where it is installed by Dockerfile. But to run it locally you have to install after you add it to package.json.
